# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Release

on:
  push:
    tags:
     - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binary for ${{ matrix.os }}-${{ matrix.arch }}
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: | 
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags="-X 'github.com/sho0pi/tickli/cmd.clientID=${CLIENT_ID}' -X 'github.com/sho0pi/tickli/cmd.clientSecret=${CLIENT_SECRET}'" -o tickli-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: tickli-${{ matrix.os }}-${{ matrix.arch }}
          path: tickli-${{ matrix.os }}-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binary artifact
        uses: actions/download-artifact@v4

      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: tickli-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

